### ISSUE TITLE
Can you share your polybar (or any other bar) configs?

### ISSUE THREAD

**Issue by wthrajat** [LizAinslie/dotfiles#1]

**Comment by LizAinslie** [comment]
I don't really use Polybar anymore. The old config can be found at https://github.com/LizAinslie/dotfiles/tree/snowball-old/.config/polybar but keep in mind that I don't plan on offering any support or updating it. If you want the "bar" as seen in the screenshots on this repository and elsewhere use the `eww` configs and have it open the `bar` window.

**Comment by wthrajat** [comment]
Alright! Thanks :)
